language: php
php:
  - "5.3"
  - "5.4"
  - "5.5"
  - "5.6"
before_install:
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.68.tar.gz
  - tar -xzf Image-ExifTool-9.68.tar.gz
  - cd Image-ExifTool-9.68
  - perl Makefile.PL
  - make
  - sudo make install
  - cd ..
  - exiftool -ver
install: make composer
script: ./tests/run.sh
