language: php
php:
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "8.0"
before_install:
  - wget http://www.sno.phy.queensu.ca/~phil/exiftool/Image-ExifTool-9.68.tar.gz
  - tar -xzf Image-ExifTool-9.68.tar.gz
  - cd Image-ExifTool-9.68
  - perl Makefile.PL
  - make
  - sudo make install
  - cd ..
  - exiftool -ver
install: make composer
script: ./tests/run.sh
